services:
  - type: web
    name: boresha-mama-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --production
    startCommand: cd backend && node src/migrations/run.js && node src/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: SMS_PROVIDER
        value: africastalking
      - key: AT_USERNAME
        value: sandbox
      - key: CORS_ORIGIN
        value: https://facility-dashboard-rho.vercel.app,https://county-portal.vercel.app,https://mother-7olsshamz-jobwangila254s-projects.vercel.app,https://chv-app.vercel.app
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: DATABASE_URL
        fromDatabase:
          name: boresha-mama-db
          property: connectionString

databases:
  - name: boresha-mama-db
    plan: free
    region: frankfurt
    databaseName: boresha_mama
